### ISSUE TITLE
tax status sort isnt working on investment offers table

### ISSUE THREAD

**Issue by cinthiavernekar** [ajency/growthinvest-laravel#182]
https://seedtwin.ajency.in/backoffice/investor/GIIN14591233/investor-invest

current : 
![image](https://user-images.githubusercontent.com/17116943/36137501-9fa521ca-10bb-11e8-8606-9794a2d63f46.png)

**Comment by prajay04** [comment]
sorting is removed as comma separated values are displayed in tax status.
