### ISSUE TITLE
Total number of records in users table is incorrect 

### ISSUE THREAD

**Issue by cinthiavernekar** [ajency/growthinvest-laravel#20]
http://seedtwin.ajency.in/backoffice/user/all

https://eisplatform.com/manage/#users

current : Total there are 102 records on eis site but on seedtwin only 86 are displayed

**Comment by prajay04** [comment]
There are dummy roles (Test role 1,Test Role 3,Back1 ....) which are associated to user on eis site for which number of user count is increased. This roles are not added on seedtwins.
