### ISSUE TITLE
filter issue 

### ISSUE THREAD

**Issue by cinthiavernekar** [ajency/growthinvest-laravel#289]
https://seedtwin.ajency.in/investment-opportunities/single-company

1. Apply business sector filter - select for eg. Ethical
2. Once the result is loaded untick Ethical and tick Fashion & Apparel

current : Result displayed on applying second filter is incorrect
![image](https://user-images.githubusercontent.com/17116943/38599341-bbc9bdc2-3d7d-11e8-8f07-61ace34f964c.png)

**Comment by prajay04** [comment]
Adding apply filter button
