### ISSUE TITLE
Name of the users not displayed in the name column 

### ISSUE THREAD

**Issue by cinthiavernekar** [ajency/growthinvest-laravel#4]
http://seedtwin.ajency.in/backoffice/user/all

current : 
![image](https://user-images.githubusercontent.com/17116943/34983574-0a9bd166-fad4-11e7-8b75-2368e7a46bc6.png)

![image](https://user-images.githubusercontent.com/17116943/34983584-11a6ca9c-fad4-11e7-97d8-9fecccca2d9f.png)

**Comment by prajay04** [comment]
on EIS name which is displayed is WP generated text. not the first and last name of user.
